<a href="https://colab.research.google.com/github/shubham1406/CODSOFT-Task-2/blob/main/CreditCard_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("/content/creditcard.csv")

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3980,10980,1.284388,-0.013181,0.646174,0.198985,-0.568675,-0.526121,-0.448235,-0.167709,1.773223,...,-0.101868,-0.030298,-0.081412,-0.123281,0.278808,1.064001,-0.090181,0.000481,15.95,0.0
3981,10981,1.190428,-0.122329,0.954945,0.267101,-0.971026,-0.652279,-0.612992,-0.003909,1.633117,...,-0.015001,0.127027,0.012079,0.534409,0.112179,1.004483,-0.100188,-0.004774,14.95,0.0
3982,10981,-0.725175,0.298202,1.824761,-2.587170,0.283605,-0.016617,0.153659,0.045084,-0.197611,...,-0.017097,-0.070535,-0.442861,-0.895837,0.624743,-0.510601,-0.031142,0.025564,12.95,0.0
3983,10981,1.226153,-0.129645,0.735197,0.142752,-0.703245,-0.349641,-0.612641,0.020507,1.648986,...,-0.047936,0.040196,-0.057391,-0.012386,0.187685,1.037786,-0.100081,-0.009869,15.95,0.0
3984,10981,1.145381,-0.059349,0.968088,0.267891,-0.822582,-0.597727,-0.450197,-0.119747,1.338188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3985 entries, 0 to 3984
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    3985 non-null   int64
 1   V1      3985 non-null   float64
 2   V2      3985 non-null   float64
 3   V3      3985 non-null   float64
 4   V4      3985 non-null   float64
 5   V5      3985 non-null   float64
 6   V6      3985 non-null   float64
 7   V7      3985 non-null   float64
 8   V8      3985 non-null   float64
 9   V9      3985 non-null   float64
 10  V10     3985 non-null   float64
 11  V11     3985 non-null   float64
 12  V12     3985 non-null   float64
 13  V13     3985 non-null   object
 14  V14     3985 non-null   float64
 15  V15     3984 non-null   float64
 16  V16     3984 non-null   float64
 17  V17     3984 non-null   float64
 18  V18     3984 non-null   float64
 19  V19     3984 non-null   float64
 20  V20     3984 non-null   float64
 21  V21     3984 non-null   float64
 22  V22     3984 non-null   float64
 23  V23     3984 non-null   float64
 24  V24     3984 non-null   float64
 25  V25     3984 non-null   float64
 26  V26     3984 non-null   float64
 27  V27     3983 non-null   float64
 28  V28     3983 non-null   float64
 29  Amount  3983 non-null   float64
 30  Class   3983 non-null   float64
dtypes: float64(29), int64(1), object(1)
memory usage: 965.2+ KB

In [6]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,3985.000000,3985.000000,3985.000000,3985.000000,3985.000000,3985.000000,3985.000000,3985.000000,3985.000000,3985.000000,...,3984.000000,3984.000000,3984.000000,3984.000000,3984.000000,3984.000000,3983.000000,3983.000000,3983.000000,3983.000000
mean,4882.712422,-0.342336,0.295676,0.956401,0.350787,-0.090254,0.047461,-0.011432,-0.111929,0.722008,...,-0.048892,-0.161233,-0.037283,0.015358,0.155481,0.125154,0.008020,-0.007900,67.488566,0.006026
std,4227.077341,1.575572,1.325769,1.134939,1.354066,1.191891,1.232063,1.112935,1.210856,1.239756,...,0.928970,0.636110,0.574724,0.573310,3.692894,0.514528,0.441222,0.289845,222.649726,0.077400
min,0.000000,-23.066842,-25.640527,-12.389545,-4.657545,-32.092129,-7.574798,-10.470770,-22.605711,-3.878658,...,-11.084324,-8.527145,-15.144340,-2.162523,-2.577363,-1.243924,-6.573218,-3.054085,0.000000,0.000000
25%,752.000000,-1.109297,-0.186752,0.421362,-0.467058,-0.630525,-0.647489,-0.464705,-0.202836,-0.119880,...,-0.269294,-0.537756,-0.173483,-0.328084,-0.170315,-0.279042,-0.081645,-0.022066,5.000000,0.000000
50%,6670.000000,-0.420050,0.307970,0.996323,0.285025,-0.157522,-0.182829,0.011509,0.002359,0.671395,...,-0.135355,-0.148984,-0.051309,0.081781,0.135816,0.062070,0.002918,0.019023,15.950000,0.000000
75%,9086.000000,1.122018,0.947750,1.662427,1.139576,0.330242,0.390611,0.489440,0.241252,1.465153,...,0.040743,0.213673,0.071019,0.404226,0.384123,0.413090,0.131076,0.083870,54.990000,0.000000
max,10981.000000,1.685314,8.261750,4.017561,7.380245,11.974269,21.393069,34.303177,3.877662,10.392889,...,22.588989,4.534454,13.876221,1.215279,231.480000,3.517346,4.173387,4.157934,7712.430000,1.000000

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       2
V28       2
Amount    2
Class     2
dtype: int64

In [8]:
df["V3"].fillna(df['V3'].mode()[0],inplace = True)

In [9]:
df["V4"].fillna(df['V4'].mode()[0],inplace = True)

In [10]:
df["V5"].fillna(df['V5'].mode()[0],inplace = True)

In [11]:
df["V6"].fillna(df['V6'].mode()[0],inplace = True)

In [12]:
df["V7"].fillna(df['V7'].mode()[0],inplace = True)

In [13]:
df["V8"].fillna(df['V8'].mode()[0],inplace = True)

In [14]:
df["V9"].fillna(df['V9'].mode()[0],inplace = True)

In [15]:
df["V10"].fillna(df['V10'].mode()[0],inplace = True)

In [16]:
df["V11"].fillna(df['V11'].mode()[0],inplace = True)
df["V12"].fillna(df['V12'].mode()[0],inplace = True)
df["V13"].fillna(df['V13'].mode()[0],inplace = True)
df["V14"].fillna(df['V14'].mode()[0],inplace = True)
df["V15"].fillna(df['V15'].mode()[0],inplace = True)
df["V16"].fillna(df['V16'].mode()[0],inplace = True)
df["V17"].fillna(df['V17'].mode()[0],inplace = True)
df["V18"].fillna(df['V18'].mode()[0],inplace = True)
df["V19"].fillna(df['V19'].mode()[0],inplace = True)
df["V20"].fillna(df['V20'].mode()[0],inplace = True)

In [17]:
df["V21"].fillna(df['V21'].mode()[0],inplace = True)
df["V22"].fillna(df['V22'].mode()[0],inplace = True)
df["V23"].fillna(df['V23'].mode()[0],inplace = True)
df["V24"].fillna(df['V24'].mode()[0],inplace = True)
df["V25"].fillna(df['V25'].mode()[0],inplace = True)
df["V26"].fillna(df['V26'].mode()[0],inplace = True)
df["V27"].fillna(df['V27'].mode()[0],inplace = True)
df["V28"].fillna(df['V28'].mode()[0],inplace = True)
df["Amount"].fillna(df['Amount'].mode()[0],inplace = True)
df["Class"].fillna(df['Class'].mode()[0],inplace = True)

In [18]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [19]:
#Distribution of legit transactions & fraudulent transactions
df['Class'].value_counts()

0.0    3961
1.0      24
Name: Class, dtype: int64

This dataset is unbalanced 0--> Normal transactions 1--> fraudulent transactions

[ ]

In [20]:
# separating data for the analysis
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [21]:
print(legit.shape)

(3961, 31)

In [22]:
print(fraud.shape)

(24, 31)

In [23]:
legit.Amount.describe()

count    3961.000000
mean       67.253517
std       221.374643
min         0.000000
25%         5.000000
50%        15.980000
75%        55.000000
max      7712.430000
Name: Amount, dtype: float64

In [24]:
fraud.Amount.describe()

count      24.000000
mean      100.740833
std       379.628808
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [25]:
#Compare the values for both transactions
df.groupby('Class').mean()

<ipython-input-25-fa55e1480041>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4866.975511,-0.337708,0.279413,0.992133,0.324529,-0.086993,0.060053,0.002541,-0.116798,0.736307,...,0.029868,-0.051796,-0.160736,-0.036717,0.016691,0.156019,0.124247,0.005409,-0.009478,67.253517
1.0,7479.958333,-1.106160,2.979698,-4.940863,4.684407,-0.628373,-2.030734,-2.317600,0.691543,-1.637972,...,0.291887,0.422272,-0.237937,-0.128553,-0.187417,0.076796,0.290312,0.437504,0.253876,100.740833

Under sampling method is use for unbalanced data

Building a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

In [26]:
legit_sample = legit.sample(n=38)

Concatinating two Dtaframes

In [27]:
new_dataset =pd.concat([legit_sample, fraud],axis=0)

In [28]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
104,69,-1.766645,2.352984,-0.009955,-0.363736,1.460953,-0.204833,0.905819,-3.384123,0.388546,...,1.964253,-0.883218,-0.247698,-0.758606,0.086450,0.202790,-0.898858,-0.944337,0.76,0.0
591,442,-0.753360,0.547357,0.632550,-1.728280,0.937092,-1.065111,1.511596,-0.279074,-0.591727,...,-0.266660,-1.073149,0.092292,-0.437549,-0.146387,0.387434,-0.061505,0.110388,77.98,0.0
3156,9364,-9.569935,4.604564,-0.343721,-1.685656,-0.604805,-1.045435,2.264632,-1.904746,10.392889,...,-2.546080,-0.152756,0.302658,0.822740,1.685001,0.045601,0.450048,-0.416946,0.01,0.0
2278,7368,-1.021093,0.665677,-0.099778,-1.504694,2.983551,3.116603,0.755787,0.612019,0.348569,...,-0.496475,-1.538870,-0.089619,0.922402,0.487409,0.050616,-0.202835,0.067166,74.98,0.0
3382,9926,1.098611,0.268880,-0.045418,1.279738,0.164792,-0.688385,0.475068,-0.415328,1.035185,...,-0.140718,-0.296244,-0.244655,-0.149466,0.765090,-0.379305,-0.037095,0.024869,105.75,0.0

In [29]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
2882,8757,-1.863756,3.442644,-4.468260,2.805336,-2.118412,-2.332285,-4.261237,1.701682,-1.439396,...,0.667927,-0.516242,-0.012218,0.070614,0.058504,0.304883,0.418012,0.208858,1.00,1.0
2894,8808,-4.617217,1.695694,-3.114372,4.328199,-1.873257,-0.989908,-4.577265,0.472216,0.472017,...,0.481830,0.146023,0.117039,-0.217565,-0.138776,-0.424453,-1.002041,0.890780,1.10,1.0
2911,8878,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00,1.0
2915,8886,-2.535852,5.793644,-7.618463,6.395830,-0.065210,-3.136372,-3.104557,1.823233,-3.878658,...,0.716720,-0.448060,-0.402407,-0.288835,1.011752,0.425965,0.413140,0.308205,1.00,1.0
2983,9064,-3.499108,0.258555,-4.489558,4.853894,-6.974522,3.628382,5.431271,-1.946734,-0.775680,...,-1.052368,0.204817,-2.119007,0.170279,-0.393844,0.296367,1.985913,-0.900452,1809.68,1.0

In [30]:
new_dataset['Class'].value_counts()

0.0    38
1.0    24
Name: Class, dtype: int64

In [31]:
new_dataset.groupby('Class').mean()

<ipython-input-31-586b59598b15>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4657.631579,-0.566431,0.311936,1.138575,0.056365,0.052047,-0.156087,0.264305,-0.649686,0.788317,...,-0.028558,-0.035840,-0.276099,-0.238710,0.061255,0.068511,0.035782,-0.071486,-0.140121,80.834737
1.0,7479.958333,-1.106160,2.979698,-4.940863,4.684407,-0.628373,-2.030734,-2.317600,0.691543,-1.637972,...,0.291887,0.422272,-0.237937,-0.128553,-0.187417,0.076796,0.290312,0.437504,0.253876,100.740833

In [32]:
#Splitting the data into Features & Targets
x=new_dataset.drop(columns='Class',axis=1)
y=new_dataset['Class']

In [33]:
print(x)

      Time        V1        V2        V3        V4        V5        V6  \
104     69 -1.766645  2.352984 -0.009955 -0.363736  1.460953 -0.204833
591    442 -0.753360  0.547357  0.632550 -1.728280  0.937092 -1.065111
3156  9364 -9.569935  4.604564 -0.343721 -1.685656 -0.604805 -1.045435
2278  7368 -1.021093  0.665677 -0.099778 -1.504694  2.983551  3.116603
3382  9926  1.098611  0.268880 -0.045418  1.279738  0.164792 -0.688385
...    ...       ...       ...       ...       ...       ...       ...
2882  8757 -1.863756  3.442644 -4.468260  2.805336 -2.118412 -2.332285
2894  8808 -4.617217  1.695694 -3.114372  4.328199 -1.873257 -0.989908
2911  8878 -2.661802  5.856393 -7.653616  6.379742 -0.060712 -3.131550
2915  8886 -2.535852  5.793644 -7.618463  6.395830 -0.065210 -3.136372
2983  9064 -3.499108  0.258555 -4.489558  4.853894 -6.974522  3.628382

            V7        V8         V9  ...       V20       V21       V22  \
104   0.905819 -3.384123   0.388546  ...  0.072645  1.964253 -0.883218
591   1.511596 -0.279074  -0.591727  ...  0.032888 -0.266660 -1.073149
3156  2.264632 -1.904746  10.392889  ...  3.486126 -2.546080 -0.152756
2278  0.755787  0.612019   0.348569  ...  0.007750 -0.496475 -1.538870
3382  0.475068 -0.415328   1.035185  ...  0.088127 -0.140718 -0.296244
...        ...       ...        ...  ...       ...       ...       ...
2882 -4.261237  1.701682  -1.439396  ...  0.360924  0.667927 -0.516242
2894 -4.577265  0.472216   0.472017  ... -0.039046  0.481830  0.146023
2911 -3.103570  1.778492  -3.831154  ...  0.399097  0.734775 -0.435901
2915 -3.104557  1.823233  -3.878658  ...  0.408704  0.716720 -0.448060
2983  5.431271 -1.946734  -0.775680  ... -3.042626 -1.052368  0.204817

           V23       V24       V25       V26       V27       V28   Amount
104  -0.247698 -0.758606  0.086450  0.202790 -0.898858 -0.944337     0.76
591   0.092292 -0.437549 -0.146387  0.387434 -0.061505  0.110388    77.98
3156  0.302658  0.822740  1.685001  0.045601  0.450048 -0.416946     0.01
2278 -0.089619  0.922402  0.487409  0.050616 -0.202835  0.067166    74.98
3382 -0.244655 -0.149466  0.765090 -0.379305 -0.037095  0.024869   105.75
...        ...       ...       ...       ...       ...       ...      ...
2882 -0.012218  0.070614  0.058504  0.304883  0.418012  0.208858     1.00
2894  0.117039 -0.217565 -0.138776 -0.424453 -1.002041  0.890780     1.10
2911 -0.384766 -0.286016  1.007934  0.413196  0.280284  0.303937     1.00
2915 -0.402407 -0.288835  1.011752  0.425965  0.413140  0.308205     1.00
2983 -2.119007  0.170279 -0.393844  0.296367  1.985913 -0.900452  1809.68

[62 rows x 30 columns]

In [34]:
print(y)

104     0.0
591     0.0
3156    0.0
2278    0.0
3382    0.0
       ...
2882    1.0
2894    1.0
2911    1.0
2915    1.0
2983    1.0
Name: Class, Length: 62, dtype: float64

Spliting the data into Traning data & Testing data

In [35]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,stratify = y,random_state=2)

In [36]:
print(x.shape,x_train.shape,x_test.shape)

(62, 30) (49, 30) (13, 30)

Model Training (Logist Regression Model)

In [37]:
model =LogisticRegression()

In [38]:
#Training the Logistic Regression Model for Training data
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

In [39]:
#accuracy on traning data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [40]:
print('Accuracy on Training Data :',training_data_accuracy)

Accuracy on Training Data : 1.0

In [41]:
#accuracy on testing data
x_test_prediction = model.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction,y_test)

In [42]:
print('Accuracy on Testing Data :',testing_data_accuracy)

Accuracy on Testing Data : 1.0